---
Standards:
  - 
    Title: Working with Generative AI
    Description: What are Generative AIs & Large Learning Models, and how are they used?
    UID: 6e38c08c-7cdb-11ee-b962-0242ac120002
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 6e38c51e-7cdb-11ee-b962-0242ac120002
        Path: /generative-ai-overview/generative-ai-overview.md
  -
    Title: Prompting Basics & Using ChatGPT
    Description: Setting up & using ChatGPT, techniques to improve responses, and how to verify information
    UID: 3a90ca66-83ea-11ee-b962-0242ac120002
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 4d2e6b4c-83ea-11ee-b962-0242ac120002
        Path: /prompting-101/making-requests-from-chatgpt.md
      -
        Type: Lesson
        UID: 4d2e6dd6-83ea-11ee-b962-0242ac120002
        Path: /prompting-101/improving-chatGPTs-responses.md
      -
        Type: Lesson
        UID: c2e2d742-83ea-11ee-b962-0242ac120002
        Path: /prompting-101/verifying-information-from-chatGPT.md
  - 
    Title: Debugging with ChatGPT
    Description: Where is ChatGPT useful in our debugging toolbox? How do we evaluate ChatGPT's responses?
    UID: e2dfab5e-952b-11ee-b9d1-0242ac120002
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: ebd7c520-952b-11ee-b9d1-0242ac120002
        Path: /debugging-w-chatgpt/debugging-w-chatgpt.md
  -
    Title: Using The OpenAI API
    Description: How do we leverage the OpenAI API to introduce generative AI into our projects?
    UID: 0182dc79-daa0-4cf6-bf14-ba0a98292f95
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 0370ba94-6324-413e-9c1b-7b2db283f643
        Path: /working-with-ai-apis/intro-to-ai-apis.md
      -
        Type: Lesson
        UID: eca69a0b-e630-4766-acd5-4a3992f89b9d
        Path: /working-with-ai-apis/getting-ready-to-use-ai-apis.md
      -
        Type: Lesson
        UID: d603955b-a208-412b-bb9d-2511bf48f589 
        Path: /working-with-ai-apis/setting-up-ai-apis-postman.md
      -
        Type: Lesson
        UID: 735f527b-865b-4878-b67b-af9af8a2100a 
        Path: /working-with-ai-apis/ai-api-models.md
      -
        Type: Lesson
        UID: 522ec902-9f54-4c8e-9848-47a8d8d80de8
        Path: /working-with-ai-apis/text-completion-endpoints.md
      -
        Type: Lesson
        UID: 08cc5b97-3408-4e71-8b47-aecbde2cb458
        Path: /working-with-ai-apis/ai-apis-in-projects.md
  - 
    Title: Using GitHub's Copilot
    Description: How do we work with code-specific AI Assistants like GitHub's Copilot?
    UID: 3b2a1fa7-b684-47f8-a465-fbcc278b4a9b
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 3b2a1fa7-b684-47f8-a465-fbcc278b4a9b
        Path: /working-w-copilot/setting-up-copilot.md
      -
        Type: Lesson
        UID: e3e38130-72f1-4695-8aa9-e9f4a2d14c58
        Path: /working-w-copilot/copilot-interface-shortcuts.md
      -
        Type: Lesson
        UID: d070c172-d08a-4548-93da-ba629a15d766
        Path: /working-w-copilot/copilot-in-projects-new-code.md
      -
        Type: Lesson
        UID: d02d6d74-c6cd-11ee-a506-0242ac120002
        Path: /working-w-copilot/copilot-in-projects-refactoring.md